### ISSUE TITLE
Difference with debug enabled deadlocks on compareArray

### ISSUE THREAD

**Issue by afking** [google/go-cmp#104]
Enabling the debug flag can cause lock contention as `compareArray` can loop on itself calling `diff.Difference` twice: https://github.com/google/go-cmp/blob/master/cmp/compare.go#L403

```
goroutine 5 [semacquire]:
sync.runtime_SemacquireMutex(0x4dffcc4, 0x900000000)
	GOROOT/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0x4dffcc0)
	GOROOT/src/sync/mutex.go:134 +0x153
repo.jazznetworks.com/jazz/main/vendor/github.com/google/go-cmp/cmp/internal/diff.(*debugger).Lock(0x4dffcc0)
	vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go:78 +0x7b
repo.jazznetworks.com/jazz/main/vendor/github.com/google/go-cmp/cmp/internal/diff.(*debugger).Begin(0x4dffcc0, 0x1, 0x1, 0xc000328550, 0xc0003466d8, 0xc000346708, 0xc00032e810)
	vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go:82 +0x54
repo.jazznetworks.com/jazz/main/vendor/github.com/google/go-cmp/cmp/internal/diff.Difference(0x1, 0x1, 0xc000328550, 0x1, 0x3, 0xc000326540)
	vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go:200 +0x381
repo.jazznetworks.com/jazz/main/vendor/github.com/google/go-cmp/cmp.(*state).compareArray(0xc000342850, 0x477cd20, 0xc00032ad40, 0x197, 0x477cd20, 0xc0001a6c40, 0x197, 0x4947940, 0x477cd20)
	vendor/github.com/google/go-cmp/cmp/compare.go:403 +0x3e3
repo.jazznetworks.com/jazz/main/vendor/github.com/google/go-cmp/cmp.(*state).compareAny(0xc000342850, 0x477cd20, 0xc00032ad40, 0x197, 0x477cd20, 0xc0001a6c40, 0x197)
	vendor/github.com/google/go-cmp/cmp/compare.go:272 +0x1189
repo.jazznetworks.com/jazz/main/vendor/github.com/google/go-cmp/cmp.(*state).statelessCompare(0xc000342850, 0x477cd20, 0xc00032ad40, 0x197, 0x477cd20, 0xc0001a6c40, 0x197, 0x4102374, 0xc00032cf00)
	vendor/github.com/google/go-cmp/cmp/compare.go:181 +0x149
repo.jazznetworks.com/jazz/main/vendor/github.com/google/go-cmp/cmp.(*state).compareArray.func1(0x0, 0x0, 0x4933420, 0xc0000d4008)
	vendor/github.com/google/go-cmp/cmp/compare.go:405 +0x170
repo.jazznetworks.com/jazz/main/vendor/github.com/google/go-cmp/cmp/internal/diff.(*debugger).Begin.func1(0x0, 0x0, 0x1, 0x10)
	vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go:97 +0x141
repo.jazznetworks.com/jazz/main/vendor/github.com/google/go-cmp/cmp/internal/diff.Difference(0x1, 0x1, 0xc000326500, 0x1, 0x2, 0xc00032ade0)
	vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go:216 +0x693
repo.jazznetworks.com/jazz/main/vendor/github.com/google/go-cmp/cmp.(*state).compareArray(0xc000342850, 0x477bda0, 0xc00032ad60, 0x97, 0x477bda0, 0xc00032ad80, 0x97, 0x4947940, 0x477bda0)
	vendor/github.com/google/go-cmp/cmp/compare.go:403 +0x3e3
repo.jazznetworks.com/jazz/main/vendor/github.com/google/go-cmp/cmp.(*state).compareAny(0xc000342850, 0x477bda0, 0xc00032ad60, 0x97, 0x477bda0, 0xc00032ad80, 0x97)
	vendor/github.com/google/go-cmp/cmp/compare.go:272 +0x1189
repo.jazznetworks.com/jazz/main/vendor/github.com/google/go-cmp/cmp.Equal(0x477bda0, 0xc00032ad60, 0x477bda0, 0xc00032ad80, 0xc00032ada0, 0x2, 0x2, 0x46c6b3a)
	vendor/github.com/google/go-cmp/cmp/compare.go:87 +0xda
repo.jazznetworks.com/jazz/main/vendor/github.com/google/go-cmp/cmp.Diff(0x477bda0, 0xc00032ad60, 0x477bda0, 0xc00032ad80, 0x0, 0x0, 0x0, 0x1, 0xc000040120)
	vendor/github.com/google/go-cmp/cmp/compare.go:101 +0x182
repo.jazznetworks.com/jazz/main/vendor/gocloud.dev/blob/drivertest.testList.func4(0xc000374000)
	vendor/gocloud.dev/blob/drivertest/drivertest.go:346 +0x619
testing.tRunner(0xc000374000, 0xc000348000)
	GOROOT/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
	GOROOT/src/testing/testing.go:878 +0x65a
```

**Comment by dsnet** [comment]
Are you reporting this because:
1) you were trying to debug the `cmp` library itself and noticed this?
2) you happened to have the `debug` tag set for an unrelated purpose and then noticed this?

**Comment by afking** [comment]
Second option, this was a side effect I didn't expect.

**Comment by dsnet** [comment]
Copy. The trivial fix is to change the build tag to something more specific (e.g., `debugcmp`).

**Comment by afking** [comment]
Would be happy for that, not a big deal I just turned off the debug flags while testing.
