### ISSUE TITLE
Error at init when running on Windows ARM

### ISSUE THREAD

**Issue by anacrolix** [google/go-cmp#359]
When running a Windows x64 binary on Windows ARM, I get this error during startup:
```
panic: regexp: Compile(`[_\p{L}][_\p{L}\p{N}]*$`): error parsing regexp: invalid character class range: `\p{L}`

goroutine 1 [running]:
regexp.MustCompile({0x7ff66897b52c, 0x17})
	/opt/homebrew/Cellar/go/1.22.3/libexec/src/regexp/regexp.go:317 +0xb4
github.com/google/go-cmp/cmp/internal/function.init()
	/Users/anacrolix/go/pkg/mod/github.com/google/go-cmp@v0.6.0/cmp/internal/function/func.go:68 +0x7c
```

It's very possible this is an upstream issue with golang/go, but I thought I'd start here.

**Comment by dsnet** [comment]
Hi, thanks for reporting the issue, but this is almost certainly a upstream issue.

**Comment by anacrolix** [comment]
Okay I think it's safe to say the issue is upstream. Thanks!
